{
    "name": "Surpay Base",
    "summary": "Modulo base de configuracion para integraciones Surpay",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "author": "Surpay",
    "license": "LGPL-3",
    "depends": ["base", "contacts", "mail", "web"],
    "data": [
        "security/surpay_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_cron_data.xml",
        "data/ir_sequence_data.xml",
        "views/provider_config_views.xml",
        "views/api_client_views.xml",
        "views/commission_rule_views.xml",
        "views/payment_transaction_views.xml",
        "views/cash_closure_views.xml",
        "views/payment_reconciliation_views.xml",
        "views/payment_reconciliation_event_wizard_views.xml",
        "views/cash_closure_transfer_confirm_wizard_views.xml",
        "views/cash_closure_report_wizard_views.xml",
        "views/cash_closure_report_templates.xml",
        "views/internal_sale_templates.xml",
        "views/pwa_templates.xml",
        "views/integration_docs_templates.xml",
    ],
    "installable": True,
    "application": True,
}
