[options]
# Encryption key for provider credentials (Fernet format).
# Replace this value per environment before deploying.
surpay_encryption_key = wsU4bKe375r4P7Vb_JbplGcDkI1fsur_Kj2BnEs75eo=
admin_passwd = CHANGE_ME
db_name=surpay_dev
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
#dbfilter = .*
list_db = False
log_level = debug
max_cron_threads = 1
limit_time_cpu = 120
limit_time_real = 240
workers = 0
xmlrpc_port = 8069
longpolling_port = 8072
