[options]
# Encryption key for provider credentials (Fernet format)
surpay_encryption_key = L2AZq0JeEYJa-Q4FMZQ6VEZgA3_y6-kL2AZq0JeEYJa=
admin_passwd = admin
db_name=surpay_dev
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
#dbfilter = .*
list_db = False
log_level = debug
max_cron_threads = 1
limit_time_cpu = 120
limit_time_real = 240
workers = 0
xmlrpc_port = 8069
longpolling_port = 8072
